
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsCOLFE_FTSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsCOLFEFTSoap {


    /**
     * 
     * @param tipo
     * @param reg
     * @param numFac
     * @param prefijo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegistroFactura", action = "http://tempuri.org/RegistroFactura")
    @WebResult(name = "RegistroFacturaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RegistroFactura", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegistroFactura")
    @ResponseWrapper(localName = "RegistroFacturaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegistroFacturaResponse")
    public String registroFactura(
        @WebParam(name = "Reg", targetNamespace = "http://tempuri.org/")
        String reg,
        @WebParam(name = "NumFac", targetNamespace = "http://tempuri.org/")
        String numFac,
        @WebParam(name = "Tipo", targetNamespace = "http://tempuri.org/")
        String tipo,
        @WebParam(name = "Prefijo", targetNamespace = "http://tempuri.org/")
        String prefijo);

    /**
     * 
     * @param tipo
     * @param reg
     * @param numFac
     * @param prefijo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GenerarXMLFacturacion", action = "http://tempuri.org/GenerarXMLFacturacion")
    @WebResult(name = "GenerarXMLFacturacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GenerarXMLFacturacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerarXMLFacturacion")
    @ResponseWrapper(localName = "GenerarXMLFacturacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GenerarXMLFacturacionResponse")
    public String generarXMLFacturacion(
        @WebParam(name = "Reg", targetNamespace = "http://tempuri.org/")
        String reg,
        @WebParam(name = "NumFac", targetNamespace = "http://tempuri.org/")
        String numFac,
        @WebParam(name = "Tipo", targetNamespace = "http://tempuri.org/")
        String tipo,
        @WebParam(name = "Prefijo", targetNamespace = "http://tempuri.org/")
        String prefijo);

    /**
     * 
     * @param codVerifica
     * @param reg
     * @param numFac
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidaFacturaAuto", action = "http://tempuri.org/ValidaFacturaAuto")
    @WebResult(name = "ValidaFacturaAutoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ValidaFacturaAuto", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidaFacturaAuto")
    @ResponseWrapper(localName = "ValidaFacturaAutoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidaFacturaAutoResponse")
    public String validaFacturaAuto(
        @WebParam(name = "Reg", targetNamespace = "http://tempuri.org/")
        String reg,
        @WebParam(name = "NumFac", targetNamespace = "http://tempuri.org/")
        String numFac,
        @WebParam(name = "codVerifica", targetNamespace = "http://tempuri.org/")
        String codVerifica);

    /**
     * 
     * @param password
     * @param prefijo
     * @param numeroFactura
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaXML", action = "http://tempuri.org/ConsultaXML")
    @WebResult(name = "ConsultaXMLResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaXML", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaXML")
    @ResponseWrapper(localName = "ConsultaXMLResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaXMLResponse")
    public String consultaXML(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Prefijo", targetNamespace = "http://tempuri.org/")
        String prefijo,
        @WebParam(name = "NumeroFactura", targetNamespace = "http://tempuri.org/")
        String numeroFactura);

    /**
     * 
     * @param password
     * @param prefijo
     * @param numeroFactura
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConsultaPDF", action = "http://tempuri.org/ConsultaPDF")
    @WebResult(name = "ConsultaPDFResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultaPDF", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaPDF")
    @ResponseWrapper(localName = "ConsultaPDFResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaPDFResponse")
    public String consultaPDF(
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "Prefijo", targetNamespace = "http://tempuri.org/")
        String prefijo,
        @WebParam(name = "NumeroFactura", targetNamespace = "http://tempuri.org/")
        String numeroFactura);

}
