
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsCOLFE_FT", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://34.215.136.170/FE_WS_FT/wsCOLFE_FT.asmx?WSDL")
public class WsCOLFEFT
    extends Service
{

    private final static URL WSCOLFEFT_WSDL_LOCATION;
    private final static WebServiceException WSCOLFEFT_EXCEPTION;
    private final static QName WSCOLFEFT_QNAME = new QName("http://tempuri.org/", "wsCOLFE_FT");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://34.215.136.170/FE_WS_FT/wsCOLFE_FT.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCOLFEFT_WSDL_LOCATION = url;
        WSCOLFEFT_EXCEPTION = e;
    }

    public WsCOLFEFT() {
        super(__getWsdlLocation(), WSCOLFEFT_QNAME);
    }

    public WsCOLFEFT(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCOLFEFT_QNAME, features);
    }

    public WsCOLFEFT(URL wsdlLocation) {
        super(wsdlLocation, WSCOLFEFT_QNAME);
    }

    public WsCOLFEFT(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCOLFEFT_QNAME, features);
    }

    public WsCOLFEFT(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCOLFEFT(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsCOLFEFTSoap
     */
    @WebEndpoint(name = "wsCOLFE_FTSoap")
    public WsCOLFEFTSoap getWsCOLFEFTSoap() {
        return super.getPort(new QName("http://tempuri.org/", "wsCOLFE_FTSoap"), WsCOLFEFTSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsCOLFEFTSoap
     */
    @WebEndpoint(name = "wsCOLFE_FTSoap")
    public WsCOLFEFTSoap getWsCOLFEFTSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wsCOLFE_FTSoap"), WsCOLFEFTSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCOLFEFT_EXCEPTION!= null) {
            throw WSCOLFEFT_EXCEPTION;
        }
        return WSCOLFEFT_WSDL_LOCATION;
    }

}
